### ISSUE TITLE
AppRun: Permission denied

### ISSUE THREAD

**Issue by probonopd** [MarvellousSoft/MarvInc#253]
Getting `AppRun: Permission denied when trying to run` the AppImage. Are you sure chmod +x is set on the `AppRun` file inside the AppImage?

References:
* https://github.com/AppImage/appimage.github.io/pull/535
* https://travis-ci.org/AppImage/appimage.github.io/builds/397192542#L632

**Comment by RenatoGeh** [comment]
You are correct, we didn't in fact `chmod +x AppRun` our AppImages. It's curious though how we had previously done tests on other machines and this error hadn't come up.

Commit 73d681784969544810b42975b0c7334a846eb0a8 should resolve this issue. You can pull the latest AppImage from here: https://github.com/MarvellousSoft/MarvInc/releases/download/v1.3.0/Marvellous_Inc-x86_64.AppImage

Please let us know if this has fixed your issue.

**Comment by probonopd** [comment]
Unfortunately still the same error in 1.3.1:
https://travis-ci.org/AppImage/appimage.github.io/builds/397875160#L632

**Comment by rilifon** [comment]
@yancouto have we corrected this on the new patch?

**Comment by rilifon** [comment]
@RenatoGeh is this still an open issue?
